# Generated by Django 2.2 on 2019-04-30 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('comparible', models.URLField()),
                ('co_author_email', models.CharField(max_length=100)),
                ('co_author_instructions', models.TextField()),
                ('cover', models.ImageField(blank=True, upload_to='cover_image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='books.Author')),
                ('co_author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='co_author', to='books.Author')),
            ],
        ),
    ]
