# Generated by Django 2.2 on 2019-05-07 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20190507_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='co_author_email',
        ),
        migrations.AddField(
            model_name='book',
            name='co_author_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Author'),
        ),
    ]
